//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alice.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alice.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required &quot;{1}&quot; attribute of &quot;{0}&quot; element is missed..
        /// </summary>
        internal static string XParse_AttributeMissed {
            get {
                return ResourceManager.GetString("XParse_AttributeMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read date value from &quot;{1}&quot; attribute of &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_DateAttribiteExpected {
            get {
                return ResourceManager.GetString("XParse_DateAttribiteExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t locate element by path: &quot;{0}&quot;..
        /// </summary>
        internal static string XParse_ElementNotFound {
            get {
                return ResourceManager.GetString("XParse_ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read enumeration value from &quot;{1}&quot; attribute of &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_EnumerationAttributeExpected {
            get {
                return ResourceManager.GetString("XParse_EnumerationAttributeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read logical value from &quot;{1}&quot; attribute of {0} element..
        /// </summary>
        internal static string XParse_LogicalAttributeExpected {
            get {
                return ResourceManager.GetString("XParse_LogicalAttributeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read numeral value from &quot;{1}&quot; attribute of &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_NumeralAttributeExpected {
            get {
                return ResourceManager.GetString("XParse_NumeralAttributeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least and only one child element expected for &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_OneChildElementExpected {
            get {
                return ResourceManager.GetString("XParse_OneChildElementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least and only one child element with name &quot;{1}&quot; expected for &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_OneExactChildElementExpected {
            get {
                return ResourceManager.GetString("XParse_OneExactChildElementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read ordinal value from &quot;{1}&quot; attribute of &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_OrdinalAttributeExpected {
            get {
                return ResourceManager.GetString("XParse_OrdinalAttributeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read character value from &quot;{1}&quot; attribute of &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_SymbolAttributeExpected {
            get {
                return ResourceManager.GetString("XParse_SymbolAttributeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read unique identifier value from &quot;{1}&quot; attribute of &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_UIDAttributeExpected {
            get {
                return ResourceManager.GetString("XParse_UIDAttributeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or one child element expected for &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_ZeroOrOneChildElementExpected {
            get {
                return ResourceManager.GetString("XParse_ZeroOrOneChildElementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or one child element with name &quot;{1}&quot; expected for &quot;{0}&quot; element..
        /// </summary>
        internal static string XParse_ZeroOrOneExactChildElementExpected {
            get {
                return ResourceManager.GetString("XParse_ZeroOrOneExactChildElementExpected", resourceCulture);
            }
        }
    }
}
